image: openjdk:11

stages:
  - build
  - publish

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  PACKAGE_NAME: "live-chat-sdk"
  PACKAGE_VERSION: "1.0.0"
  GROUP_ID: "com.gitlab.mitek"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew

build:
  stage: build
  script:
    - ./gradlew build

publish:
  stage: publish
  script:
    - ./gradlew publish
  only:
    - main
